{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Ingesting Data\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Ingest some data\n",
    "\n",
    "*Clean up any previous ingest:* If you have previously used this notebook to ingest the sample data into your data cube you will find the ingest data on your filesystem. This should be deleted. As ingest takes a significant amount of time the notebook doesn't include clean up commands and you should remove the files from your host. The ingest file places them under `easi-training-pc/output/ingest_data`"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Ingest LS7 data\n",
    "\n",
    "The sample data for LS7 is a single timeslice so ingestion won't take long. We'll use that as a first example, then we will do the LS8 sample data, which will take a LOT longer.\n",
    "\n",
    "Whilst ingestion takes a while it is because it is performing all the reprojections required against the scene to ensure all your data ready for analysis in your chosen projection. When you just index those reprojections still need to be done, but they are done when you load. With ingestion, all that repeated projection can be done just once and from then on loading and use will be a lot faster."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "fatal: not a git repository: /home/jovyan/odc/../.git/modules/datacube-core\n",
      "/home/jovyan/.local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use \"pip install psycopg2-binary\" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.\n",
      "  \"\"\")\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "/home/jovyan/odc/datacube/api/grid_workflow.py:291: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future\n",
      "  numpy.array([key], dtype='datetime64[ns]'),\n",
      "2018-11-29 01:49:07,270 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-143_-76_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-143_-76_20151212102823557965.nc'\n",
      "2018-11-29 01:49:12,820 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-142_-76_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-142_-76_20151212102823557965.nc'\n",
      "2018-11-29 01:49:16,455 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-144_-75_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-144_-75_20151212102823557965.nc'\n",
      "2018-11-29 01:49:31,049 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-143_-75_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-143_-75_20151212102823557965.nc'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2018-11-29 01:49:46,032 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-142_-75_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-142_-75_20151212102823557965.nc'\n",
      "2018-11-29 01:49:50,489 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-141_-75_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-141_-75_20151212102823557965.nc'\n",
      "2018-11-29 01:50:02,691 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-143_-74_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-143_-74_20151212102823557965.nc'\n",
      "2018-11-29 01:50:22,617 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-142_-74_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-142_-74_20151212102823557965.nc'\n",
      "2018-11-29 01:50:32,469 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-141_-74_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-141_-74_20151212102823557965.nc'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2018-11-29 01:50:36,411 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-143_-73_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-143_-73_20151212102823557965.nc'\n",
      "2018-11-29 01:50:51,568 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-142_-73_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-142_-73_20151212102823557965.nc'\n",
      "2018-11-29 01:51:01,611 481 datacube-ingest ERROR Failed to create storage unit file (Exception: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-141_-73_20151212102823557965.nc') \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 323, in process_tasks\n",
      "    executor.result(future)\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/.local/lib/python3.6/site-packages/six.py\", line 693, in reraise\n",
      "    raise value\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 37, in get_ready\n",
      "    result = SerialExecutor.result(futures[0])\n",
      "  File \"/home/jovyan/odc/datacube/executor.py\", line 64, in result\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/scripts/ingest.py\", line 269, in ingest_work\n",
      "    storage_config=config['storage'])\n",
      "  File \"/home/jovyan/odc/datacube/drivers/netcdf/driver.py\", line 53, in write_dataset_to_storage\n",
      "    **kwargs)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 638, in write_dataset_to_netcdf\n",
      "    netcdfparams)\n",
      "  File \"/home/jovyan/odc/datacube/storage/storage.py\", line 585, in create_netcdf_storage_unit\n",
      "    nco = netcdf_writer.create_netcdf(str(filename), **(netcdfparams or {}))\n",
      "  File \"/home/jovyan/odc/datacube/storage/netcdf_writer.py\", line 57, in create_netcdf\n",
      "    nco = Dataset(netcdf_path, 'w', **kwargs)\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 2015, in netCDF4._netCDF4.Dataset.__init__\n",
      "  File \"netCDF4/_netCDF4.pyx\", line 1636, in netCDF4._netCDF4._ensure_nc_success\n",
      "PermissionError: [Errno 13] Permission denied: b'/home/project/datcube/ingested_data/LS7_SR/LS7_SR_3577_-141_-73_20151212102823557965.nc'\n",
      "0 successful, 0 failed\n"
     ]
    }
   ],
   "source": [
    "!datacube ingest -c ~/work/data-pipelines/landsat-usgs/ls7_ledaps_usgs_netcdf_ingest.yaml"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Ingest LS8 data\n",
    "\n",
    "This will take a while...even with two processors being used."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# !datacube ingest -c /home/jovyan/work/data-pipelines/landsat-usgs/ls8_usgs_sr_albers_netcdf_ingest.yaml --executor multiproc 2"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
